### ISSUE TITLE
Availability Zones are Not Universal

### ISSUE THREAD

**Issue by osterman** [jsonmaur/aws-regions#1]
AWS randomizes AZs across accounts to ensure even distribution. Case in point, your list omits `us-east-1b`, but it's valid for our account. See more here: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

![image](https://cloud.githubusercontent.com/assets/52489/19174943/7fbdacce-8be7-11e6-9a16-e3ce77b1b6cc.png)

![image](https://cloud.githubusercontent.com/assets/52489/19174922/48a337c2-8be7-11e6-84e5-2aa587a15944.png)

`aws ec2 describe-availability-zones  --region us-east-1`

![image](https://cloud.githubusercontent.com/assets/52489/19174912/38975e12-8be7-11e6-808b-53a535be91aa.png)

**Comment by jsonmaur** [comment]
Oh interesting, I didn't know they did that. I'll get that updated. Thanks!

**Comment by jsonmaur** [comment]
Fixed via https://github.com/jsonmaur/aws-regions/commit/538fea78caf052f07eb4ecc1c28b11c16f7bb7c3.
