### ISSUE TITLE
missing go module support

### ISSUE THREAD

**Issue by xh3b4sd** [jsonmaur/aws-regions#16]
Hi there, right now we need to import this amazing library like this in our `go.mod` files. 

```
	github.com/jsonmaur/aws-regions/go v0.0.0-20200521181458-43baf1be9a5a
```

It would be nice to have a more proper versioning like this. 

```
	github.com/jsonmaur/aws-regions/go v2.2.0
```

Though when we do that we get a little error like below. The issue is that the module structure has to be respected in versions greater than v2.0.0. <3

```
$ go mod tidy
go: errors parsing go.mod:
/Users/xh3b4sd/go/src/github.com/giantswarm/awscnfm/go.mod:17: require github.com/jsonmaur/aws-regions/go: version "v2.2.0" invalid: unknown revision go/v2.2.0
```

The following does also not work. 

```
	github.com/jsonmaur/aws-regions/go/v2 v2.2.0
```

```
go mod tidy
go: github.com/jsonmaur/aws-regions/go/v2@v2.2.0: reading github.com/jsonmaur/aws-regions/go/go/go.mod at revision go/v2.2.0: unknown revision go/v2.2.0
```

**Comment by jsonmaur** [comment]
Apologies for the delay on this... wasn't aware of the requirement Go modules put in place for versions >=2 using a `v2` folder. It's fixed now. You can import the versioned library with:
```go
import "github.com/jsonmaur/aws-regions/v2"
```
