### ISSUE TITLE
No "pretty name" for Regions

### ISSUE THREAD

**Issue by calvcoll** [jsonmaur/aws-regions#9]
Can we add a "pretty name" for regions to the objects? (e.g not just a "ireland" or "sao-paulo" but "Ireland" and "São Paulo" would be returned).

**Comment by jsonmaur** [comment]
I'd be happy to accept a PR for this.

**Comment by jsonmaur** [comment]
In fact, I would shorten `pretty_name` and just call it `name`.

**Comment by jsonmaur** [comment]
This was updated in v2.
